version: '3'

networks:
  zupMGMNetwork:

volumes:
  redis-data:

services:
  docker-postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    container_name: docker-postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - zupMGMNetwork
    restart: always

  docker-redis:
    image: redis
    container_name: docker-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "micronaut123", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    networks:
      - zupMGMNetwork
    restart: always